### PR TITLE
Responsive Design: Page Contents fix

### PR DESCRIPTION
**Pull request by kailoon**
- As requested, this fix is only for responsive layout. 
- Other viewports are left untouched.
- This is meant for issue #14

### CODE REVIEW

**Comment by captn3m0** [comment]
A lot of pages don't look responsive:

image

It gets worse on smaller screens, but there shouldn't be any horizontal scrolling required on any mobile device.

**Comment by kailoon** [comment]
Sorry for the oversight. 

I fix the horizontal scrolling on all pages, it is due to the `pre` tag. However, the fix is not perfect visually due to the usage of background image with has a design limitation for smaller screen size. 
image

The footer navigation is optimised as well.

Question: When you said _A lot of pages don't look responsive_ you mean there are hundreds of them or? I only found 6 pages on the site. Maybe I am missing something?

Hope this solve the responsive issue.

**Comment by captn3m0** [comment]
I meant that the index.html and 00.html pages looked pretty decent, but the rest of them (1-5) did not (probably due to the `pre` tag only being present in the latter pages). But the images on the latter pages also didn't seem responsive, hence my comment.

I checked with the new changes, and it looks much better - the images look decent.

Can we fix the subheader situation as well perhaps?

image

I'd have also liked if the command prompt background images could be resized for mobile devices, but that doesn't seem worth the effort.

Happy to merge with the subheader fix.

**Comment by kailoon** [comment]
Understood.

Subheader is fixed.

The command prompt is a bit tricky due to the way it is structured.

Hope this help.

**Review by captn3m0 — APPROVED** [review]

**Pull request merged**
